spring.application.name=BackendBooking2

spring.datasource.url=jdbc:mysql://localhost:3306/booking_db
spring.datasource.username=bo
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

server.servlet.session.timeout=50m


server.error.include-binding-errors=always
server.error.include-message=always
server.error.include-stacktrace=always

app.user.name=Harun12
app.user.password=HarunKodeOrd123